name: build-web-site

on:
  push:
    branches:
      - main

jobs:
  StyleCheck:
    name: Style and Voice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Style check
      uses: errata-ai/vale-action@v1.3.0
      with:
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env: 
        MARP_VERSION: 0.21.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - run: sudo  wget -qO- https://github.com/marp-team/marp-cli/releases/download/v0.21.1/marp-cli-v$MARP_VERSION-linux.tar.gz | tar xvz
      - run: chmod +x marp && export

  ls:
    name: ls
    runs-on: ubuntu-latest
                        
    steps:
                    
      - name: ls
        run: ls